/** Roteiros dos 5 estágios — formações, mergulhos, alvos no chão e chefes. */

function e(at, spawn, extra = {}) {
  return { at, spawn, ...extra };
}

export const STAGES = [
  {
    boss: "albatroz",
    waves: [
      e(1.2, "line", { kind: "vespa", n: 2, x0: 42, gap: 58, pattern: "down" }),
      e(1.3, "line", { kind: "vespa", n: 2, x0: 250, gap: 58, pattern: "down" }),
      e(4.4, "line", { kind: "vespa", n: 4, x0: 36, gap: 92, pattern: "down" }),
      e(7.6, "swoop", { kind: "gaviao", n: 2, side: "left" }),
      e(10.8, "line", { kind: "vespa", n: 4, x0: 40, gap: 90, pattern: "sine" }),
      e(14.0, "single", { kind: "as", x: 180, pattern: "hover" }),
      e(17.2, "swoop", { kind: "gaviao", n: 2, side: "right" }),
      e(20.4, "v", { kind: "vespa", n: 5 }),
      e(23.6, "single", { kind: "bufalo", x: 160, pattern: "down" }),
      e(26.8, "line", { kind: "artilheiro", n: 2, x0: 100, gap: 140, pattern: "aim" }),
      e(30.0, "single", { kind: "bufalo", x: 220, pattern: "down" }),
      e(31.6, "swoop", { kind: "gaviao", n: 3, side: "left" }),
      e(32.4, "swoop", { kind: "gaviao", n: 3, side: "right" }),
      e(34.2, "boss", { kind: "albatroz" }),
    ],
  },
  {
    boss: "sentinela",
    waves: [
      e(0.8, "ground", { kind: "ninho", x: 70 }),
      e(0.8, "ground", { kind: "ninho", x: 290 }),
      e(1.4, "line", { kind: "vespa", n: 6, x0: 40, gap: 52, pattern: "down" }),
      e(4.0, "swoop", { kind: "gaviao", n: 4, side: "left" }),
      e(6.0, "swoop", { kind: "gaviao", n: 4, side: "right" }),
      e(8.5, "v", { kind: "artilheiro", n: 5 }),
      e(11.0, "single", { kind: "as", x: 90, pattern: "sine" }),
      e(12.5, "line", { kind: "bufalo", n: 2, x0: 90, gap: 160, pattern: "down" }),
      e(15.0, "ground", { kind: "ninho", x: 180 }),
      e(16.0, "line", { kind: "vespa", n: 7, x0: 30, gap: 48, pattern: "sine" }),
      e(19.5, "swoop", { kind: "gaviao", n: 5, side: "left" }),
      e(21.0, "v", { kind: "vespa", n: 6 }),
      e(23.4, "boss", { kind: "sentinela" }),
    ],
  },
  {
    boss: "serpente",
    waves: [
      e(1.0, "v", { kind: "vespa", n: 7 }),
      e(3.2, "line", { kind: "artilheiro", n: 4, x0: 55, gap: 80, pattern: "aim" }),
      e(5.8, "swoop", { kind: "gaviao", n: 5, side: "right" }),
      e(8.0, "single", { kind: "bufalo", x: 80, pattern: "down" }),
      e(8.6, "single", { kind: "bufalo", x: 180, pattern: "down" }),
      e(9.2, "single", { kind: "bufalo", x: 280, pattern: "down" }),
      e(12.0, "single", { kind: "as", x: 220, pattern: "hover" }),
      e(13.0, "line", { kind: "vespa", n: 8, x0: 28, gap: 42, pattern: "down" }),
      e(16.0, "swoop", { kind: "gaviao", n: 4, side: "left" }),
      e(16.4, "swoop", { kind: "gaviao", n: 4, side: "right" }),
      e(19.5, "ground", { kind: "ninho", x: 110 }),
      e(19.5, "ground", { kind: "ninho", x: 250 }),
      e(22.0, "v", { kind: "artilheiro", n: 5 }),
      e(25.5, "boss", { kind: "serpente" }),
    ],
  },
  {
    boss: "tempestade",
    waves: [
      e(0.6, "line", { kind: "gaviao", n: 4, x0: 50, gap: 80, pattern: "dive" }),
      e(2.4, "swoop", { kind: "gaviao", n: 6, side: "left" }),
      e(4.5, "line", { kind: "artilheiro", n: 5, x0: 40, gap: 70, pattern: "aim" }),
      e(7.0, "v", { kind: "vespa", n: 9 }),
      e(9.5, "single", { kind: "as", x: 160, pattern: "hover" }),
      e(10.5, "single", { kind: "as", x: 260, pattern: "sine" }),
      e(12.0, "line", { kind: "bufalo", n: 3, x0: 70, gap: 110, pattern: "down" }),
      e(15.0, "swoop", { kind: "gaviao", n: 6, side: "right" }),
      e(17.5, "line", { kind: "vespa", n: 6, x0: 40, gap: 55, pattern: "sine" }),
      e(20.0, "ground", { kind: "ninho", x: 60 }),
      e(20.2, "ground", { kind: "ninho", x: 180 }),
      e(20.4, "ground", { kind: "ninho", x: 300 }),
      e(23.5, "boss", { kind: "tempestade" }),
    ],
  },
  {
    boss: "nadir",
    waves: [
      e(0.8, "v", { kind: "vespa", n: 7 }),
      e(2.6, "swoop", { kind: "gaviao", n: 5, side: "left" }),
      e(3.2, "swoop", { kind: "gaviao", n: 5, side: "right" }),
      e(6.0, "line", { kind: "artilheiro", n: 5, x0: 40, gap: 70, pattern: "aim" }),
      e(8.5, "single", { kind: "bufalo", x: 90, pattern: "down" }),
      e(9.0, "single", { kind: "bufalo", x: 270, pattern: "down" }),
      e(11.0, "single", { kind: "as", x: 180, pattern: "hover" }),
      e(12.5, "ground", { kind: "ninho", x: 80 }),
      e(12.7, "ground", { kind: "ninho", x: 280 }),
      e(14.0, "line", { kind: "vespa", n: 8, x0: 30, gap: 42, pattern: "down" }),
      e(17.0, "swoop", { kind: "gaviao", n: 6, side: "left" }),
      e(19.5, "v", { kind: "artilheiro", n: 7 }),
      e(22.0, "line", { kind: "bufalo", n: 3, x0: 60, gap: 120, pattern: "down" }),
      e(25.0, "single", { kind: "as", x: 120, pattern: "hover" }),
      e(25.6, "single", { kind: "as", x: 240, pattern: "hover" }),
      e(29.0, "boss", { kind: "nadir" }),
    ],
  },
];
